<?php

namespace app\admin\controller;

use app\common\model\Category;
use think\Controller;

class Article extends Controller
{

	protected $db;

	public function _initialize ()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->db = new \app\common\model\Article();
	}

	//首页
	public function index ()
	{
		$field = $this->db->getAll();
		$this->assign('field',$field);
		return $this->fetch();
	}

	//添加
	public function store ()
	{
		if ( request()->isPost() ) {
			$res = $this->db->store( input( 'post.' ) );
			if ( $res[ 'valid' ] ) {
				//说明执行成功
				$this->success( $res[ 'msg' ] , 'index' );
				exit;
			}
			else {
				//执行失败
				$this->error( $res[ 'msg' ] );
				exit;
			}
		}
		//1.获取分类数据
		$cateData = ( new Category() )->getAll();
		$this->assign( 'cateData' , $cateData );
		//2.获取标签数据
		$tagData = db( 'tag' )->select();
		$this->assign( 'tagData' , $tagData );

		return $this->fetch();
	}
}
