<?php
return array (
  6 => 
  array (
    'catid' => '6',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '6,10,11,12',
    'catname' => '后盾新闻',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'houdunnews',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=lists&catid=6',
    'items' => '4',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"houdunwang","category_template":"category_news","list_template":"list_news","show_template":"show_news","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '1',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'houdunxinwen',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '14',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '9,13,14,15',
    'catname' => '后盾产品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'houdunchanpin',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=lists&catid=9',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"houdunwang","category_template":"category_chanpin","list_template":"list_chanpin","show_template":"show_chanpin","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'houdunchanpin',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  10 => 
  array (
    'catid' => '10',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '6',
    'arrparentid' => '0,6',
    'child' => '0',
    'arrchildid' => '10',
    'catname' => '最新新闻',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'houdunnews/',
    'catdir' => 'hotnews',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=lists&catid=10',
    'items' => '2',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"houdunwang","category_template":"category_news","list_template":"list_news","show_template":"show_news","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'zuixinxinwen',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  11 => 
  array (
    'catid' => '11',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '6',
    'arrparentid' => '0,6',
    'child' => '0',
    'arrchildid' => '11',
    'catname' => '校园活动',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'houdunnews/',
    'catdir' => 'school',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=lists&catid=11',
    'items' => '2',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"houdunwang","category_template":"category_news","list_template":"list_news","show_template":"show_news","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '11',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xiaoyuanhuodong',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  12 => 
  array (
    'catid' => '12',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '6',
    'arrparentid' => '0,6',
    'child' => '0',
    'arrchildid' => '12',
    'catname' => '学员回访',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'houdunnews/',
    'catdir' => 'xueyuan',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=lists&catid=12',
    'items' => '2',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"houdunwang","category_template":"category_news","list_template":"list_news","show_template":"show_news","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '12',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xueyuanhuifang',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  13 => 
  array (
    'catid' => '13',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '14',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '0',
    'arrchildid' => '13',
    'catname' => '后盾人',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'houdunchanpin/',
    'catdir' => 'houdunren',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=lists&catid=13',
    'items' => '3',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"houdunwang","category_template":"category_chanpin","list_template":"list_chanpin","show_template":"show_chanpin","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '13',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'houdunren',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  14 => 
  array (
    'catid' => '14',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '14',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '0',
    'arrchildid' => '14',
    'catname' => '后盾论坛',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'houdunchanpin/',
    'catdir' => 'houdunluntan',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=lists&catid=14',
    'items' => '2',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"houdunwang","category_template":"category_chanpin","list_template":"list_chanpin","show_template":"show_chanpin","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '14',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'houdunluntan',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  15 => 
  array (
    'catid' => '15',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '14',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '0',
    'arrchildid' => '15',
    'catname' => '后盾网',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'houdunchanpin/',
    'catdir' => 'houdunwang',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=lists&catid=15',
    'items' => '2',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"houdunwang","category_template":"category_chanpin","list_template":"list_chanpin","show_template":"show_chanpin","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '15',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'houdunwang',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  16 => 
  array (
    'catid' => '16',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '16,17,18',
    'catname' => '单页面',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'danyemian',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=lists&catid=16',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"houdunwang","page_template":"page_about","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '16',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'danyemian',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  17 => 
  array (
    'catid' => '17',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '16',
    'arrparentid' => '0,16',
    'child' => '0',
    'arrchildid' => '17',
    'catname' => '联系我们',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'danyemian/',
    'catdir' => 'lianxiwomen',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=lists&catid=17',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"houdunwang","page_template":"page_lianxi","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '17',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'lianxiwomen',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  18 => 
  array (
    'catid' => '18',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '16',
    'arrparentid' => '0,16',
    'child' => '0',
    'arrchildid' => '18',
    'catname' => '关于我们',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'danyemian/',
    'catdir' => 'guanyuwomen',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=lists&catid=18',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"houdunwang","page_template":"page_about","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '18',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'guanyuwomen',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
);
?>