<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '13',
    'typeid' => '0',
    'title' => '带你玩转微信公众号',
    'style' => '',
    'thumb' => 'http://localhost/my-video/phpcms/uploadfile/2017/1124/20171124015245568.png',
    'keywords' => '公众',
    'description' => '微信公众号是开发者或商家在微信公众平台上申请的应用账号，该帐号与QQ账号互通，通过公众号',
    'posids' => '0',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=show&catid=13&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1511458488',
    'updatetime' => '1511458578',
    'hitsid' => 'c-14-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '13',
    'typeid' => '0',
    'title' => 'javascript之jquery',
    'style' => '',
    'thumb' => 'http://localhost/my-video/phpcms/uploadfile/2017/1124/20171124014352721.jpg',
    'keywords' => '服务器',
    'description' => 'jQuery是一个快速、简洁的JavaScript框架，是继Prototype之后又一个优秀的JavaScript代码库（或JavaScript框架）',
    'posids' => '0',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=show&catid=13&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1511458709',
    'updatetime' => '1511458735',
    'hitsid' => 'c-14-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '13',
    'typeid' => '0',
    'title' => 'HDCMS2.0 开发',
    'style' => '',
    'thumb' => 'http://localhost/my-video/phpcms/uploadfile/2017/1124/20171124020359784.jpg',
    'keywords' => 'HDCMS2 0 开发',
    'description' => 'HDCMS2 0 全新的产品设计、快速的产品创新、超出用户期待的产品价值，基于微信 桌面 移动三网通设计模式为企业提供开发、运营、培训、推广一体化解决方案',
    'posids' => '0',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=show&catid=13&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1511459836',
    'updatetime' => '1511459896',
    'hitsid' => 'c-14-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '14',
    'typeid' => '0',
    'title' => '亲爱的盾友，感恩有你，有你真好！',
    'style' => '',
    'thumb' => 'http://localhost/my-video/phpcms/uploadfile/2017/1124/20171124020858469.jpg',
    'keywords' => '真好',
    'description' => '风雨无阻，砥砺七载，感谢所有盾友一直以来的支持与厚爱无以为报，唯有为大家奉献更优质的WEB开发学习资料后盾PHP培训感恩节大回馈，即日起',
    'posids' => '0',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=show&catid=14&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1511460491',
    'updatetime' => '1511460542',
    'hitsid' => 'c-14-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '14',
    'typeid' => '0',
    'title' => '试用期16000元!试用期16000元!',
    'style' => '',
    'thumb' => 'http://localhost/my-video/phpcms/uploadfile/2017/1124/20171124021049783.jpg',
    'keywords' => '试用期16000元!试用期16000元!',
    'description' => '  被标题吸引过来的小伙伴们~我没疯，只不过，有个好消息要着急告诉大家，在前几天毕业的81期学员中（目前毕业一周左右），有同学已经找',
    'posids' => '0',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=show&catid=14&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1511460603',
    'updatetime' => '1511460652',
    'hitsid' => 'c-14-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '15',
    'typeid' => '0',
    'title' => '实训班学员展示独立开发完成的移动端项目、大型商城项目',
    'style' => '',
    'thumb' => 'http://localhost/my-video/phpcms/uploadfile/2017/1124/20171124021233219.jpg',
    'keywords' => '项目 学员 商城',
    'description' => '项目介绍 后盾网学员全部独立开发开发学员：吕辉项目阶段：82期项目项目介绍：该项目是学员的毕业项目之一，采用PHP+MYSQL架构。后盾每位',
    'posids' => '0',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=show&catid=15&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1511460698',
    'updatetime' => '1511460756',
    'hitsid' => 'c-14-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '15',
    'typeid' => '0',
    'title' => 'CMS三网通项目、基于laravel+vue的在线视频系统、前端项目展示',
    'style' => '',
    'thumb' => 'http://localhost/my-video/phpcms/uploadfile/2017/1124/20171124021427842.jpg',
    'keywords' => '项目 网通 前端',
    'description' => '项目介绍 后盾网学员全部独立开发开发学员：黄志成项目阶段：81期项目项目介绍：该项目是学员的毕业项目之一，采用PHP+MYSQL架构。后盾每',
    'posids' => '0',
    'url' => 'http://localhost/my-video/phpcms/index.php?m=content&c=index&a=show&catid=15&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1511460801',
    'updatetime' => '1511460870',
    'hitsid' => 'c-14-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>