<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" name="viewport"/>
    <title></title>
    <link rel="stylesheet" type="text/css" href="{{ARTICLE_URL}}/mlibs/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="{{ARTICLE_URL}}/mlibs/css/hongbang.css"/>
    <script src="{{ARTICLE_URL}}/mlibs/js/jquery.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="{{ARTICLE_URL}}/mlibs/js/bootstrap.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="{{ARTICLE_URL}}/mlibs/js/index.js" type="text/javascript" charset="utf-8"></script>
</head>
<body>
<!--头部-->
<include file='ARTICLE_PATH/mheader'/>
<!--头部结束-->
<div class="main">
    <table cellpadding="0" cellspacing="0" class="table">
        <tr>
            <th>姓名</th>
            <th width="28%">公司</th>
            <th>毕业时间</th>
            <th>毕业薪资</th>
            <th>目前薪资</th>
            <th>地点</th>
        </tr>
        <tr>
            <td>张*</td>
            <td>应同学要求保密</td>
            <td>2015.11</td>
            <td>22000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>王勇</td>
            <td>唐顿国际咨询顾问(北京)有限公司</td>
            <td>2016.05</td>
            <td>20000</td>
            <td>&nbsp;</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>王敬龙</td>
            <td>应同学要求保密</td>
            <td>2015.11</td>
            <td>17000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>刘欢</td>
            <td>中视博艺（北京）文化传媒有限责任公司</td>
            <td>2016.03</td>
            <td>15000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>唐付红</td>
            <td>应同学要求保密</td>
            <td>2015.09</td>
            <td>17000</td>
            <td><br/>
            </td>
            <td>泰国</td>
        </tr>
        <tr>
            <td>赵书伟</td>
            <td>应同学要求保密</td>
            <td>2015.09</td>
            <td>17000</td>
            <td><br/>
            </td>
            <td>泰国</td>
        </tr>
        <tr>
            <td>王涛</td>
            <td>应同学要求保密</td>
            <td>2015.09</td>
            <td>16000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>李亚龙</td>
            <td>旺旺集团</td>
            <td>2015.08</td>
            <td>7500</td>
            <td>15000<br/></td>
            <td>上海</td>
        </tr>
        <tr>
            <td>任聪聪</td>
            <td>应同学要求保密</td>
            <td>2016.03</td>
            <td>12000</td>
            <td><br/>
            </td>
            <td>泰国</td>
        </tr>
        <tr>
            <td>周金花</td>
            <td>云旅人（北京）科技有限公司</td>
            <td>2015.08</td>
            <td>10000</td>
            <td>16000</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>吴艳军</td>
            <td>北京酷结网</td>
            <td>2014.11</td>
            <td>8000</td>
            <td>15000+</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>向*</td>
            <td>某知名培训机构讲师</td>
            <td>2014.11</td>
            <td>15000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>何乐</td>
            <td>上海菜苗网络科技有限公司</td>
            <td>2014.06</td>
            <td>15000</td>
            <td><br/>
            </td>
            <td>上海</td>
        </tr>
        <tr>
            <td>曹广义</td>
            <td>上海烽容网络有限公司</td>
            <td>2014.06</td>
            <td>14000</td>
            <td><br/>
            </td>
            <td>上海</td>
        </tr>
        <tr>
            <td>于洋</td>
            <td>唯想互联</td>
            <td>2015.11</td>
            <td>13000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>韩东宇</td>
            <td>e袋洗</td>
            <td>2016.01</td>
            <td>13000</td>
            <td>15000</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>张峰</td>
            <td>北京***有限公司</td>
            <td>2014.03</td>
            <td>13000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>刘欢</td>
            <td>中视博艺（北京）文化传媒有限责任公司</td>
            <td>2016.03</td>
            <td>15000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>刘敏</td>
            <td>北京****管理有限公司</td>
            <td>2016.03</td>
            <td>12000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>宫东洋</td>
            <td>应同学要求保密</td>
            <td>2016.01</td>
            <td>12000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>邢志龙</td>
            <td>北京兴长信达科技公司</td>
            <td>2016.03</td>
            <td>12000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>刘小龙</td>
            <td>深圳国途启航教育科技有限公司</td>
            <td>2016.03</td>
            <td>12000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>刘豪贵</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>12000+</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>赖文邦</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>12000+</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>李坤</td>
            <td>应同学要求保密</td>
            <td>2014.03</td>
            <td>12000</td>
            <td>17000</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>陈曾强</td>
            <td>应同学要求保密</td>
            <td>2014.06</td>
            <td>7000</td>
            <td>22000+</td>
            <td>泰国</td>
        </tr>
        <tr>
            <td>阿不来提</td>
            <td>合丰文化传播有限公司</td>
            <td>2016.03</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>泰国</td>
        </tr>
        <tr>
            <td>白俊遥</td>
            <td>应同学要求保密</td>
            <td>2015.01</td>
            <td>8000</td>
            <td>15000</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>高晓斌</td>
            <td>特立行（北京）科技有限公司</td>
            <td>2014.08</td>
            <td>9000</td>
            <td>13000</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>曾新东</td>
            <td>北京邦美科技</td>
            <td>2014.12</td>
            <td>7000</td>
            <td>12000+</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>李勇</td>
            <td>起讯名扬(北京)科技有限公司</td>
            <td>2014.12</td>
            <td>6000</td>
            <td>12000+</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>景兆红</td>
            <td>北京百万新娘科技</td>
            <td>2014.12</td>
            <td>6000</td>
            <td>10000+</td>
            <td>上海</td>
        </tr>
        <tr>
            <td>康俊杰</td>
            <td>兰花国际</td>
            <td>2015.11</td>
            <td>11000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>巩持新</td>
            <td>北京**文化传播有限公司</td>
            <td>2016.04</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>高建波</td>
            <td>应同学要求保密</td>
            <td>2016.03</td>
            <td>9500</td>
            <td><br/>
            </td>
            <td>泰国</td>
        </tr>
        <tr>
            <td>李泓毅</td>
            <td>应同学要求保密</td>
            <td>2016.01</td>
            <td>12000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>李德旺</td>
            <td>北京金色号角影视策划有限公司</td>
            <td>2016.04</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>李改霞</td>
            <td>大象群文化传媒有限公司</td>
            <td>2016.04</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>韩强</td>
            <td>应同学要求保密</td>
            <td>2016.04</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>赵俊</td>
            <td>东莞市创客联盟网络科技有限公司</td>
            <td>2016.01</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>东莞</td>
        </tr>
        <tr>
            <td>孟伟</td>
            <td>北京某金融公司</td>
            <td>2016.03</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>刘睿</td>
            <td>应同学要求保密</td>
            <td>2016.01</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>河南</td>
        </tr>
        <tr>
            <td>陈广恩</td>
            <td>应同学要求保密</td>
            <td>2015.09</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>何盛再</td>
            <td>应同学要求保密</td>
            <td>2015.09</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>武迎收</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>李卓</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>余翔</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>刘笑飞</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>10000+</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>梁月</td>
            <td>API 网络科技有限公司</td>
            <td>2014.03</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>徐影</td>
            <td>北京大麦城科技有限公司</td>
            <td>2015.08</td>
            <td>10000+</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>白玉</td>
            <td>广州弘亚莱珠宝公司</td>
            <td>2014.03</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>马睿</td>
            <td>IBM</td>
            <td>2014.09</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>赖文邦</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>10000+</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>姚晓航</td>
            <td>北京游艺谷有限科技公司</td>
            <td>2014.08</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>李莎莎</td>
            <td>北京游艺谷有限科技公司</td>
            <td>2014.08</td>
            <td>10000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>马志斌</td>
            <td>聚美优品</td>
            <td>2014.11</td>
            <td>10000+</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>辛晓凯</td>
            <td>洗衣邦网</td>
            <td>2014.12</td>
            <td>9000</td>
            <td>14000</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>左小涵</td>
            <td>应同学要求保密</td>
            <td>2015.1</td>
            <td>6000</td>
            <td>12000</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>张飘飘</td>
            <td>百事看购网络科技有限公司</td>
            <td>2016.03</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>周林华</td>
            <td>应同学要求保密</td>
            <td>2015.11</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>钱坤</td>
            <td>应同学要求保密</td>
            <td>2016.01</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>张强</td>
            <td>北京国商金融</td>
            <td>2015.12</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>张津铄</td>
            <td>北京宅食科技开发有限公司</td>
            <td>2015.11</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>赵迪</td>
            <td>应同学要求保密</td>
            <td>2016.04</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>县城</td>
        </tr>
        <tr>
            <td>董壮</td>
            <td>应同学要求保密</td>
            <td>2016.01</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>周林华</td>
            <td>应同学要求保密</td>
            <td>2015.11</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>苗忠强</td>
            <td>应同学要求保密</td>
            <td>2015.11</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>刘峰</td>
            <td>应同学要求保密</td>
            <td>2015.11</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>于亚梅</td>
            <td>应同学要求保密</td>
            <td>2015.09</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>周蕊</td>
            <td>北京魔方网</td>
            <td>2015.01</td>
            <td>8000</td>
            <td>10000+</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>刘灿</td>
            <td>北京博雅科五洲科技有限公司</td>
            <td>2015.11</td>
            <td>9000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>周雨龙</td>
            <td>天津苏州欧睿来科技有限公司</td>
            <td>2016.01</td>
            <td>9000</td>
            <td><br/>
            </td>
            <td>天津</td>
        </tr>
        <tr>
            <td>王征</td>
            <td>选演员网</td>
            <td>2016.03</td>
            <td>9000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>张津烁</td>
            <td>应同学要求保密</td>
            <td>2015.11</td>
            <td>9000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>冉建勇</td>
            <td>安趣网</td>
            <td>2015.08</td>
            <td>9000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>黄丹丹</td>
            <td>北京网络白武士</td>
            <td>2015.11</td>
            <td>9000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>崔伟</td>
            <td>应同学要求保密</td>
            <td>2014.06</td>
            <td>9000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>贾晓杰</td>
            <td>北京创信软通科技有限公司</td>
            <td>2015.08</td>
            <td>9000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>陈兴</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>9000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>赵志刚</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>8500</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>刘明瑞</td>
            <td>北京我要赛信息技术有限公司</td>
            <td>2015.01</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>杨蔓</td>
            <td>应同学要求保密</td>
            <td>2016.03</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>黄佳宁</td>
            <td>北京爵维科技有限公司</td>
            <td>2015.01</td>
            <td>8000</td>
            <td>10000</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>陈星月</td>
            <td>应同学要求保密</td>
            <td>2016.03</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>赵峰</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>8000+</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>姚尧</td>
            <td>应同学要求保密</td>
            <td>2016.03</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>赵礼源</td>
            <td>无线畅联管理科技（北京）有限公司</td>
            <td>2014.11</td>
            <td>8000</td>
            <td>13000</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>杨湛</td>
            <td>应同学要求保密</td>
            <td>2016.03</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>韦海伦</td>
            <td>盈动体育</td>
            <td>2015.08</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>陈文</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>邹健</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>赵峰</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>左卫川</td>
            <td>应同学要求保密</td>
            <td>2016.03</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>黄信强</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>严晓康</td>
            <td>应同学要求保密</td>
            <td>2016.03</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>仇红娟</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>广东</td>
        </tr>
        <tr>
            <td>陈鸿</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>代丽芳</td>
            <td>应同学要求保密</td>
            <td>2016.03</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>李庆阔</td>
            <td>应同学要求保密</td>
            <td>2015.08</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>张锐</td>
            <td>壹捌捌伍(北京)国际汽车俱乐部有限公司</td>
            <td>2015.02</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>詹哲旭</td>
            <td>北京德美成网络科技有限公司</td>
            <td>2015.01</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>郭冠军</td>
            <td>金汇证券</td>
            <td>2014.12</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>李冬庆</td>
            <td>云联天地(北京)信息技术有限公司</td>
            <td>2015.01</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>魏桂强</td>
            <td>北京四方恒通管理顾问有限公司</td>
            <td>2015.02</td>
            <td>8000</td>
            <td>9000+</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>刘熠</td>
            <td>网融众信（北京）网络信息技术有限公司</td>
            <td>2014.11</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>郑生齐</td>
            <td>北京尊毫晶世</td>
            <td>2014.11</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>李貌</td>
            <td>北京汽车达人</td>
            <td>2014.11</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>王磊</td>
            <td>北京源彩科技有限公司</td>
            <td>2015.01</td>
            <td>8000</td>
            <td><br/>
            </td>
            <td>北京</td>
        </tr>
        <tr>
            <td>程聪</td>
            <td>邦美科技</td>
            <td>2014.12</td>
            <td>7000</td>
            <td>9000+</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>屈海滨</td>
            <td>用友网络科技股份有限公司</td>
            <td>2015.01</td>
            <td>6000</td>
            <td>12000</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>子云</td>
            <td>京东网</td>
            <td>2014.11</td>
            <td>6000</td>
            <td>12000</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>余磊</td>
            <td>武汉聚享互创</td>
            <td>2015.01</td>
            <td>6000</td>
            <td><br/>
            </td>
            <td>武汉</td>
        </tr>
        <tr>
            <td>郭鲲生</td>
            <td>深圳网通动力</td>
            <td>2014.12</td>
            <td>6000</td>
            <td>9000+</td>
            <td>北京</td>
        </tr>

        <tr>
            <td>周理想</td>
            <td>应同学要求保密</td>
            <td>2014.06</td>
            <td>6000</td>
            <td>8000+</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>谈际波</td>
            <td>应同学要求保密</td>
            <td>2014.06</td>
            <td>6000</td>
            <td>8000+</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>刘哲</td>
            <td>应同学要求保密</td>
            <td>2014.08</td>
            <td>6000</td>
            <td>8000+</td>
            <td>北京</td>
        </tr>
        <tr>
            <td>梁文亮</td>
            <td>应同学要求保密</td>
            <td>2016.03</td>
            <td>6000</td>
            <td></td>
            <td>湖北</td>
        </tr>
        <tr>
            <td>路庆生</td>
            <td>应同学要求保密</td>
            <td>2016.03</td>
            <td>5000</td>
            <td></td>
            <td>北京</td>
        </tr>
    </table>
</div>
</body>
</html>
